class ColibraProduct:
    def __init__(self, row) -> None:
        self.productId = row[0]
        self.prodcutCode = row[1]
        self.active = row[2]
        self.name = row[3]
        self.price = row[4]
        self.currency = row[5]
        self.vat = row[6]
        self.unit = row[7]
        self.category = row[8]
        self.producer = row[9]
        self.weight = row[10]
        self.ean = row[11]
        self.shortDescription = row[12]
        self.description = row[13]
        self.stock = row[14]
        self.img1 = '' if not row[15] else row[15]
        self.img2 = '' if not row[16] else row[16]
        self.img3 = '' if not row[17] else row[17]
        self.img4 = '' if not row[18] else row[18]
        self.img5 = '' if not row[19] else row[19]
        self.img6 = '' if not row[20] else row[20]
        self.img7 = '' if not row[21] else row[21]